export enum KafkaTopics {
  AUTH_USER_CREATED = 'auth.user.created',
  AUTH_USER_UPDATED = 'auth.user.updated',
  AUTH_USER_DELETED = 'auth.user.deleted',
  EVENT_CREATED = 'event.created',
  EVENT_UPDATED = 'event.updated',
  EVENT_DELETED = 'event.deleted',
  // Follower-fanout topics: emitted alongside the raw EVENT_UPDATED/DELETED
  // above, carrying the pre-resolved follower list so notifications-svc never
  // has to query events-svc's database directly.
  EVENT_UPDATED_FOR_FOLLOWERS = 'event.updated.for-followers',
  EVENT_DELETED_FOR_FOLLOWERS = 'event.deleted.for-followers',
  EVENT_ANNOUNCEMENT = 'event.announcement',
  EVENT_REMINDER_DUE = 'event.reminder-due',
  NOTIFICATION_SENT = 'notification.sent',
  NOTIFICATION_FAILED = 'notification.failed',
  NOTIFICATION_BROADCAST = 'notification.broadcast',
  NOTIFICATION_BROADCAST_DISPATCHED = 'notification.broadcast-dispatched',
  NOTIFICATION_BROADCAST_BATCH = 'notification.broadcast-batch',
  NOTIFICATION_BROADCAST_BATCH_COMPLETED = 'notification.broadcast-batch-completed',
}

export interface UserCreatedEvent {
  userId: string;
  email: string;
  name: string;
  createdAt: Date;
}

export interface UserUpdatedEvent {
  userId: string;
  email?: string;
  name?: string;
  updatedAt: Date;
}

export interface UserDeletedEvent {
  userId: string;
  deletedAt: Date;
}

export interface EventCreatedEvent {
  eventId: string;
  userId: string;
  title: string;
  description: string;
  date: Date;
  createdAt: Date;
}

export interface EventUpdatedEvent {
  eventId: string;
  userId: string;
  title?: string;
  description?: string;
  date?: Date;
  updatedAt: Date;
}

export interface EventDeletedEvent {
  eventId: string;
  userId: string;
  deletedAt: Date;
}

// Shared shape for every follower-fanout topic (update/delete/announce/reminder)
// — events-svc resolves followerUserIds itself since notifications-svc can't
// query events-svc's database.
export interface EventFollowerNotifyEvent {
  eventId: string;
  title: string;
  body: string;
  followerUserIds: string[];
}

export interface NotificationSentEvent {
  notificationId: string;
  userId: string;
  eventId: string;
  title: string;
  body: string;
  sentAt: Date;
}

export interface NotificationFailedEvent {
  notificationId: string;
  userId: string;
  eventId: string;
  error: string;
  failedAt: Date;
}

// Fire-and-forget: an admin requests a push to ALL users. The gateway emits this
// on NOTIFICATION_BROADCAST and returns 202 immediately; the notifications worker
// consumes it and fans out to every device token in FCM multicast batches.
export interface NotificationBroadcastEvent {
  broadcastId: string; // generated by the gateway so the run can be tracked end-to-end
  title: string;
  body: string;
  data?: Record<string, string>;
  eventId?: string;
  requestedBy: string; // admin userId, for audit
  requestedAt: Date;
}

// Emitted by the dispatcher once it has finished paging the DeviceToken table
// and knows how many batches this broadcast will produce. Lets analytics-svc
// create the run record with the expected totals up front.
export interface NotificationBroadcastDispatchedEvent {
  broadcastId: string;
  title: string;
  body: string;
  requestedBy: string;
  requestedAt: Date;
  batches: number;
  totalTokens: number;
  dispatchedAt: Date;
}

// One page of a broadcast fanout. The dispatcher (broadcast()) keyset-paginates
// the DeviceToken table and emits one of these per 500-token page; a single
// worker in the notifications consumer group handles each batch.
export interface NotificationBroadcastBatchEvent {
  broadcastId: string; // correlates all batches of one broadcast
  batchId: string; // Kafka message key → even worker spread
  title: string;
  body: string;
  data?: Record<string, string>;
  eventId?: string;
  tokens: { token: string; userId: string }[]; // up to 500 (FCM multicast limit)
}

// Emitted by the worker after it finishes a batch, stamped with the instance
// that processed it (INSTANCE_ID ?? os.hostname()).
export interface NotificationBroadcastBatchCompletedEvent {
  broadcastId: string;
  batchId: string;
  processedBy: string;
  sent: number;
  failed: number;
  completedAt: Date;
}
