#!/usr/bin/env bash
# Generates a .env file with cryptographically random secrets.
# Idempotent: refuses to overwrite an existing .env unless --force is passed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
EXAMPLE="$ROOT/.env.example"
FORCE=0

if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
  FORCE=1
fi

if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
  echo "$ENV_FILE already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

gen() {
  # 32 random bytes -> base64 (44 chars), URL-safe substitutions for shell safety.
  local v
  v="$(openssl rand -base64 48 | tr -d '\n' | tr '/+' '_-')"
  echo "$v"
}

gen_hex() {
  local len="${1:-32}"
  openssl rand -hex "$len"
}

umask 077

umask 077

# Generate every secret into local variables first so the heredoc can
# reference the fresh values (don't depend on the old .env being present).
P_POSTGRES_SUPERUSER_PASSWORD=$(gen)
P_POSTGRES_AUTH_PASSWORD=$(gen)
P_POSTGRES_EVENTS_PASSWORD=$(gen)
P_POSTGRES_NOTIFICATIONS_PASSWORD=$(gen)
P_REDIS_ADMIN_PASSWORD=$(gen)
P_REDIS_APP_PASSWORD=$(gen)
P_REDIS_HEALTH_PASSWORD=$(gen)
P_KAFKA_ADMIN_PASSWORD=$(gen)
P_KAFKA_APP_PASSWORD=$(gen)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file is gitignored. Do not commit. Rotate by running this script again.

# --- Postgres (infrastructure) ---
POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERUSER_PASSWORD=$P_POSTGRES_SUPERUSER_PASSWORD
POSTGRES_SUPERUSER_DB=postgres

POSTGRES_AUTH_USER=auth_app
POSTGRES_AUTH_PASSWORD=$P_POSTGRES_AUTH_PASSWORD

POSTGRES_EVENTS_USER=events_app
POSTGRES_EVENTS_PASSWORD=$P_POSTGRES_EVENTS_PASSWORD

POSTGRES_NOTIFICATIONS_USER=notifications_app
POSTGRES_NOTIFICATIONS_PASSWORD=$P_POSTGRES_NOTIFICATIONS_PASSWORD

# --- Redis (infrastructure) ---
REDIS_ADMIN_USER=redis_admin
REDIS_ADMIN_PASSWORD=$P_REDIS_ADMIN_PASSWORD
REDIS_APP_USER=redis_app
REDIS_APP_PASSWORD=$P_REDIS_APP_PASSWORD
REDIS_HEALTH_USER=redis_health
REDIS_HEALTH_PASSWORD=$P_REDIS_HEALTH_PASSWORD

# --- Kafka (infrastructure) ---
KAFKA_ADMIN_USER=kafka_admin
KAFKA_ADMIN_PASSWORD=$P_KAFKA_ADMIN_PASSWORD
KAFKA_APP_USER=kafka_app
KAFKA_APP_PASSWORD=$P_KAFKA_APP_PASSWORD

# --- App-facing service URLs (consumed by the NestJS apps) ---
# The apps run inside the docker network, so they reach the data services
# directly on their internal TLS-enabled ports.
KAFKA_BROKER=kafka:29093

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$P_REDIS_APP_PASSWORD

AUTH_DATABASE_URL=postgresql://auth_app:$P_POSTGRES_AUTH_PASSWORD@postgres:5432/auth_db?schema=public
EVENTS_DATABASE_URL=postgresql://events_app:$P_POSTGRES_EVENTS_PASSWORD@postgres:5432/events_db?schema=public
NOTIFICATIONS_DATABASE_URL=postgresql://notifications_app:$P_POSTGRES_NOTIFICATIONS_PASSWORD@postgres:5432/notifications_db?schema=public

# --- TLS settings for the app (read by libs/shared + PrismaService + RedisCacheService) ---
DATABASE_SSL_MODE=require
DATABASE_SSL_CA_PATH=/etc/ssl/events-fsa/ca.crt

KAFKA_SECURITY_PROTOCOL=SSL
KAFKA_SSL_CA_PATH=/etc/ssl/events-fsa/ca.crt
# Internal NestJS apps use the SSL listener (kafka:29093) — no SASL needed.
# External clients use the SASL_SSL listener (nginx:9094) with these creds:
#   mechanism=SCRAM-SHA-256  username=\$KAFKA_APP_USER  password=below
# KAFKA_SASL_MECHANISM=SCRAM-SHA-256
# KAFKA_SASL_USERNAME=\$KAFKA_APP_USER
# KAFKA_SASL_PASSWORD=$P_KAFKA_APP_PASSWORD

REDIS_TLS=true
REDIS_TLS_CA_PATH=/etc/ssl/events-fsa/ca.crt

# --- Firebase Cloud Messaging ---
FIREBASE_PROJECT_ID=your-project-id
FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
FIREBASE_CLIENT_EMAIL=firebase-adminsdk-xxxxx@your-project-id.iam.gserviceaccount.com

# --- Auth ---
JWT_SECRET=change-me-in-production

# --- TLS material (generated by scripts/generate-certs.sh) ---
TLS_SAN_DNS=localhost,kafka,postgres,redis
TLS_SAN_IPS=127.0.0.1
# External hostnames added to each service's server cert SAN so clients can
# verify the cert when connecting through nginx from outside the docker network.
# Optional: public hostname added to each service cert SAN for external clients.
# Set before running scripts/generate-certs.sh.
# KAFKA_EXTERNAL_HOSTNAME=kafka.yourdomain.com
# POSTGRES_EXTERNAL_HOSTNAME=db.yourdomain.com
# REDIS_EXTERNAL_HOSTNAME=cache.yourdomain.com
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 600)."

# Avoid leaking secrets to the terminal.
echo
echo "Summary:"
grep -E '^[A-Z_]+(_USER|_PASSWORD)=' "$ENV_FILE" | sed 's/=.*$/=<redacted>/'
