#!/usr/bin/env bash
# Generates a .env file with cryptographically random secrets.
# Idempotent: refuses to overwrite an existing .env unless --force is passed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
EXAMPLE="$ROOT/.env.example"
FORCE=0

if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
  FORCE=1
fi

if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
  echo "$ENV_FILE already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

gen() {
  # 32 random bytes -> base64 (44 chars), URL-safe substitutions for shell safety.
  local v
  v="$(openssl rand -base64 48 | tr -d '\n' | tr '/+' '_-')"
  echo "$v"
}

gen_hex() {
  local len="${1:-32}"
  openssl rand -hex "$len"
}

umask 077

umask 077

# Generate every secret into local variables first so the heredoc can
# reference the fresh values (don't depend on the old .env being present).
P_POSTGRES_SUPERUSER_PASSWORD=$(gen)
P_POSTGRES_AUTH_PASSWORD=$(gen)
P_POSTGRES_EVENTS_PASSWORD=$(gen)
P_POSTGRES_NOTIFICATIONS_PASSWORD=$(gen)
P_JWT_SECRET=$(gen)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file is gitignored. Do not commit. Rotate by running this script again.

# --- Postgres (infrastructure) ---
POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERUSER_PASSWORD=$P_POSTGRES_SUPERUSER_PASSWORD
POSTGRES_SUPERUSER_DB=postgres

POSTGRES_AUTH_USER=auth_app
POSTGRES_AUTH_PASSWORD=$P_POSTGRES_AUTH_PASSWORD

POSTGRES_EVENTS_USER=events_app
POSTGRES_EVENTS_PASSWORD=$P_POSTGRES_EVENTS_PASSWORD

POSTGRES_NOTIFICATIONS_USER=notifications_app
POSTGRES_NOTIFICATIONS_PASSWORD=$P_POSTGRES_NOTIFICATIONS_PASSWORD

# --- App-facing service URLs (consumed by the NestJS apps) ---
# The apps run inside the docker network and reach the data services over
# plaintext on their internal ports — no TLS, no SASL, no Redis auth.
KAFKA_BROKER=kafka:29092

REDIS_HOST=redis
REDIS_PORT=6379

AUTH_DATABASE_URL=postgresql://auth_app:$P_POSTGRES_AUTH_PASSWORD@postgres:5432/auth_db?schema=public
EVENTS_DATABASE_URL=postgresql://events_app:$P_POSTGRES_EVENTS_PASSWORD@postgres:5432/events_db?schema=public
NOTIFICATIONS_DATABASE_URL=postgresql://notifications_app:$P_POSTGRES_NOTIFICATIONS_PASSWORD@postgres:5432/notifications_db?schema=public

# --- Firebase Cloud Messaging ---
FIREBASE_PROJECT_ID=your-project-id
FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
FIREBASE_CLIENT_EMAIL=firebase-adminsdk-xxxxx@your-project-id.iam.gserviceaccount.com

# --- Auth ---
JWT_SECRET=$P_JWT_SECRET

# --- Admin allowlist (api-gateway AdminGuard) ---
# Comma-separated emails allowed to create/edit/delete events, send
# announcements, and broadcast. Matches the seed script's admin account —
# change this (and re-seed) for a real deployment.
ADMIN_EMAILS=admin@eventfsa.local
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 600)."

# Avoid leaking secrets to the terminal.
echo
echo "Summary:"
grep -E '^[A-Z_]+(_USER|_PASSWORD)=' "$ENV_FILE" | sed 's/=.*$/=<redacted>/'
