user default off
user redis_admin on ~* &* +@all >t2WRaK4LmJhwNVQa9jSBHsBHEoJZwSvpAesqY2eM3tab-XAvFXJgLHQ3LS1rl7eU
user redis_app on ~* &* +@read +@write +@pubsub +@connection +@sortedset +@stream -@admin -@dangerous -@keyspace >WZKuF_m8MJ0s7ElcTdDXTl886Wi_D3ZFKOiiJtdDRMPAwjfOG0dGb0VrhVAnWjME
user redis_health on ~* &* +@connection +@read >WltlYgc9j238urJXTAsvQlVACZc4N5MJZgjDng4PIOC0McUchVt9rgUHIYHAA08I
